<?php

namespace Labs\AdminBundle\Repository;

use Labs\AdminBundle\Entity\Format;
use Labs\AdminBundle\Entity\Users;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormatRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Users $user
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getDraftUser(Users $user)
    {
        $qb = $this->createQueryBuilder('f');
        $qb->where(
            $qb->expr()->eq('f.user', ':user'),
            $qb->expr()->eq('f.draft', 0)
        );
        $qb->setParameter('user', $user);
        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @return array
     */
    public function getAll()
    {
        $qb = $this->createQueryBuilder('f');
        $qb->where('f.draft <> 0');
        $qb->orderBy('f.created', 'Desc');
        return $qb->getQuery()->getResult();
    }

    /**
     * @param Users $user
     * @param Format $format
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     * Recupere le format de l'utilisateur couramment connecté avec l'id passé en paramètre
     */
    public function getFormatForUser(Users $user, Format $format)
    {
        $qb = $this->createQueryBuilder('f');
        $qb->leftJoin('f.user', 'u');
        $qb->addSelect('u');
        $qb->where(
            $qb->expr()->eq('f.id', ':format'),
            $qb->expr()->eq('u.id', ':user')
        );
        $qb->setParameter('format', $format);
        $qb->setParameter('user', $user);
        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @param Format $format
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     * Recupere le format avec l'id passé en paramètre
     */
    public function getFormats(Format $format)
    {
        $qb = $this->createQueryBuilder('f');
        $qb->where(
            $qb->expr()->eq('f.id', ':format')
        );
        $qb->setParameter('format', $format);
        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @param $max
     * @return array
     */
    public function findFormatNum($max = null)
    {
        $qb = $this->createQueryBuilder('f');
        $qb->leftJoin('f.medias', 'm');
        $qb->addSelect('m');
        $qb->leftJoin('f.item', 'i');
        $qb->addSelect('i');
        $qb->where(
            $qb->expr()->eq('f.online', 1),
            $qb->expr()->eq('f.draft', 1)
        );
        $qb->andWhere($qb->expr()->eq('m.actived', 1));
        $qb->orderBy('f.created', 'Desc');
        if(null !== $max){
            $qb->setMaxResults($max);
        }
        return $qb->getQuery()->getResult();
    }

    /**
     * @param Format $format
     * @param $slug
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getDossierSlug(Format $format, $slug)
    {
        $qb = $this->createQueryBuilder('d');
        $qb->leftJoin('d.medias','m');
        $qb->addSelect('m');
        $qb->leftJoin('d.item','i');
        $qb->addSelect('i');
        $qb->leftJoin('i.section','s');
        $qb->addSelect('s');
        $qb->where(
            $qb->expr()->eq('d.id', ':format'),
            $qb->expr()->eq('d.slug', ':slug'),
            $qb->expr()->eq('m.actived', 1),
            $qb->expr()->eq('d.draft', 1),
            $qb->expr()->eq('d.online', 1)
        );
        $qb->setParameter('format', $format);
        $qb->setParameter('slug', $slug);
        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @param $min
     * @param null $max
     * @return array
     */
    public function OldDossier($min ,$max)
    {
        $qb = $this->createQueryBuilder('d');
        $qb->leftJoin('d.medias','m');
        $qb->addSelect('m');
        $qb->leftJoin('d.item','i');
        $qb->addSelect('i');
        $qb->where(
            $qb->expr()->neq('d.id', ':min'),
            $qb->expr()->eq('d.draft', 1),
            $qb->expr()->eq('d.online', 1)
        );
        $qb->orderBy('d.created', 'DESC');
        $qb->setMaxResults($max);
        $qb->setParameter('min', $min);
        return $qb->getQuery()->getResult();
    }
}
