<?php

namespace Labs\AdminBundle\Repository;

/**
 * InfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getAll()
    {
        $qb = $this->createQueryBuilder('i');
        $qb->orderBy('i.created', 'Desc');
        return $qb->getQuery()->getResult();
    }

    /**
     * @param $max
     * @return array
     */
    public function findInfoNum($max)
    {
        $qb = $this->createQueryBuilder('i');
        $qb->where($qb->expr()->eq('i.online', 1));
        $qb->orderBy('i.updated', 'Desc');
        $qb->setMaxResults($max);
        return $qb->getQuery()->getResult();
    }
    
}
