<?php

namespace Labs\AdminBundle\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getAll()
    {
        $qb = $this->createQueryBuilder('i');
        $qb->orderBy('i.name', 'Desc');
        return $qb->getQuery()->getResult();
    }

    /**
     * @param $id_entity
     * @return array
     */
    public function getItemsBySection($id_entity)
    {
        $qb = $this->createQueryBuilder('i');
        $qb->leftJoin('i.section', 'sec');
        $qb->where(
            $qb->expr()->eq('i.section', ':id_entity'),
            $qb->expr()->eq('i.online', 1)
        );
        $qb->setParameter(':id_entity', $id_entity);
        return $qb->getQuery()->getResult();
    }

    /**
     * @param $id
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getOne($id)
    {
        $qb = $this->createQueryBuilder('i');
        $qb->where($qb->expr()->eq('i.id', ':id'));
        $qb->setParameter(':id', $id);
        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @param $entity
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getItemAllPosts($entity)
    {
            $qb = $this->createQueryBuilder('i');
            $qb->where('i.online = 1');
            $qb->andWhere($qb->expr()->eq('i.id', ':entity'));
            $qb->setParameter(':entity', $entity);
            return $qb->getQuery()->getOneOrNullResult();
    }
}
