<?php

namespace Labs\AdminBundle\Repository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $post
     * @return array
     */
    public function findForPostMedia($post)
    {
        $qb = $this->createQueryBuilder('m');
        $qb->where(
            $qb->expr()->eq('m.post', ':post')
        );
        $qb->setParameter('post', $post);
        return $qb->getQuery()->getResult();
    }

    /**
     * @param $format
     * @return array
     */
    public function findForDossierMedia($format)
    {
        $qb = $this->createQueryBuilder('m');
        $qb->where(
            $qb->expr()->eq('m.format', ':format')
        );
        $qb->setParameter('format', $format);
        return $qb->getQuery()->getResult();
    }

    /**
     * @param $media
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneMedia($media)
    {
        $qb = $this->createQueryBuilder('m');
        $qb->where(
            $qb->expr()->eq('m.id', ':media')
        );
        $qb->setParameter('media', $media);
        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @param $id
     * @param $foreignKey
     * @return array
     */
    public function findMediaIsNotMedia($id, $foreignKey)
    {
        $qb = $this->createQueryBuilder('m');
        $qb->where(
            $qb->expr()->eq('m.post', ':foreignKey'),
            $qb->expr()->neq('m.id', ':id')
        );
        $qb->setParameter('foreignKey', $foreignKey);
        $qb->setParameter('id', $id);
        return $qb->getQuery()->getResult();
    }
}
