<?php

namespace Labs\AdminBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getDraftUser($user)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where(
            $qb->expr()->eq('p.user', ':user'),
            $qb->expr()->eq('p.draft', 0)
        );
        $qb->setParameter('user', $user);
        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @return array
     */
    public function getAll()
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.draft <> 0');
        $qb->orderBy('p.created', 'Desc');
        return $qb->getQuery()->getResult();
    }
}
