<?php

namespace Labs\AdminBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $user
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getDraftUser($user)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where(
            $qb->expr()->eq('p.user', ':user'),
            $qb->expr()->eq('p.draft', 0)
        );
        $qb->setParameter('user', $user);
        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @return array
     */
    public function getAll()
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.draft <> 0');
        $qb->orderBy('p.created', 'Desc');
        return $qb->getQuery()->getResult();
    }

    /**
     * @param $user
     * @param $post
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     * Recupere l'article de l'utilisateur couramment connecté avec l'id passé en paramètre
     */
    public function getPostForUser($user, $post)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where(
            $qb->expr()->eq('p.user', ':user'),
            $qb->expr()->eq('p.id', ':post')
        );
        $qb->setParameter('user', $user);
        $qb->setParameter('post', $post);
        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @param $post
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     * Recupere l'article avec l'id passé en paramètre
     */
    public function getPost($post)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where(
            $qb->expr()->eq('p.id', ':post')
        );
        $qb->setParameter('post', $post);
        return $qb->getQuery()->getOneOrNullResult();
    }
    
    
}
