<?php

namespace Labs\AdminBundle\Repository;


/**
 * SectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return array
     */
    public function getAll()
    {
        $qb = $this->createQueryBuilder('s');
        $qb->orderBy('s.name', 'Desc');
        return $qb->getQuery()->getResult();
    }

    /**
     * @param $id
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getOne($id)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->where($qb->expr()->eq('s.id', ':id'));
        $qb->setParameter(':id', $id);
        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @return array
     */
    public function getSectionsAndItems()
    {
            $qb = $this->createQueryBuilder('s');
            $qb->leftJoin('s.items', 'i')
                ->addSelect('i');
            $qb->where($qb->expr()->eq('s.online', 1));
            return $qb->getQuery()->getResult();
    }

    /**
     * @param $entity
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getSectionAllPosts($entity)
    {
            $qb = $this->createQueryBuilder('s');
            $qb->leftJoin('s.items', 'i')
                ->addSelect('i');
            $qb->where($qb->expr()->eq('s.online', 1));
            $qb->where($qb->expr()->eq('s.id', ':entity'));
            $qb->setParameter(':entity', $entity);
            return $qb->getQuery()->getOneOrNullResult();
    }
    
}
