<?php

namespace Labs\AdminBundle\Repository;

/**
 * SettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSettingData()
    {
        $qb = $this->createQueryBuilder('s');
        return $qb->getQuery()->getOneOrNullResult();
    }
}
