
#liip_imagine upload crop image

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        thumb_back:
            quality: 95
            filters:
                thumbnail: { size: [218, 218], mode: outbound }
                background: { size: [220, 220], position: center, color: '#EEF1F5' }
            post_processors:
                jpegoptim: { strip_all: true, max: 70, progressive: true }
                optipng: { strip_all: true, level: 5 }


        thumb_top:
            quality: 95
            filters:
                thumbnail: { size: [696, 385], mode: outbound }
            post_processors:
                jpegoptim: { strip_all: true, max: 70, progressive: true }
                optipng: { strip_all: true, level: 5 }

        thumb_top_bottom:
            quality: 95
            filters:
                thumbnail: { size: [324, 160], mode: outbound }
            post_processors:
                jpegoptim: { strip_all: true, max: 70, progressive: true }
                optipng: { strip_all: true, level: 5 }


        thumb_item_page:
            quality: 95
            filters:
                thumbnail: { size: [183, 133], mode: outbound }
                background: { size: [185, 135], position: center, color: '#EEF1F5' }
            post_processors:
                jpegoptim: { strip_all: true, max: 70, progressive: true }
                optipng: { strip_all: true, level: 5 }


        thumb_top_small:
            quality: 95
            filters:
                thumbnail: { size: [100, 70], mode: outbound }
            post_processors:
                jpegoptim: { strip_all: true, max: 70, progressive: true }
                optipng: { strip_all: true, level: 5 }


        thumb_block_article:
            quality: 95
            filters:
                thumbnail: { size: [324, 235], mode: outbound }
            post_processors:
                jpegoptim: { strip_all: true, max: 70, progressive: true }
                optipng: { strip_all: true, level: 5 }

        thumb_article_view:
            quality: 95
            filters:
                thumbnail: { size: [696, 464], mode: outbound }
            post_processors:
                jpegoptim: { strip_all: true, max: 70, progressive: true }
                optipng: { strip_all: true, level: 5 }

        thumb_article_old:
            quality: 95
            filters:
                thumbnail: { size: [218, 150], mode: outbound }
            post_processors:
                jpegoptim: { strip_all: true, max: 70, progressive: true }
                optipng: { strip_all: true, level: 5 }

        thumb_flash:
            quality: 95
            filters:
                thumbnail: { size: [316, 142], mode: outbound }
                background: { size: [318, 144], position: center, color: '#EEF1F5' }
            post_processors:
                jpegoptim: { strip_all: true, max: 70, progressive: true }
                optipng: { strip_all: true, level: 5 }


        thumb_dossier:
            quality: 95
            filters:
                thumbnail: { size: [324, 160], mode: outbound }
            post_processors:
                jpegoptim: { strip_all: true, max: 70, progressive: true }
                optipng: { strip_all: true, level: 5 }

        thumb_dossier_inner:
            quality: 95
            filters:
                thumbnail: { size: [356, 220], mode: outbound }
            post_processors:
                jpegoptim: { strip_all: true, max: 70, progressive: true }
                optipng: { strip_all: true, level: 5 }

        thumb_video:
            quality: 95
            filters:
                thumbnail: { size: [324, 160], mode: outbound }
            post_processors:
                jpegoptim: { strip_all: true, max: 70, progressive: true }
                optipng: { strip_all: true, level: 5 }


        thumb_dossier_small:
            quality: 95
            filters:
                thumbnail: { size: [286, 222], mode: outbound }
                background: { size: [288, 224], position: center, color: '#EEF1F5' }
            post_processors:
                jpegoptim: { strip_all: true, max: 70, progressive: true }
                optipng: { strip_all: true, level: 5 }


        thumb_facebook:
            quality: 100
            filters:
                thumbnail: { size: [600, 315], mode: outbound }
            post_processors:
                jpegoptim: { strip_all: true, max: 70, progressive: true }
                optipng: { strip_all: true, level: 5 }
