labs_front:
    resource: "@LabsFrontBundle/Controller/"
    type:     annotation
    prefix:   /

labs_admin:
    resource: "@LabsAdminBundle/Controller/"
    type:     annotation
    prefix:   /codepit

labs_limitless_tpl:
    resource: "@LabsLimitlessTplBundle/Controller/"
    type:     annotation
    prefix:   /tpladmin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

