labs_front:
    resource: "@LabsFrontBundle/Controller/"
    type:     annotation
    prefix:   /

labs_admin:
    resource: "@LabsAdminBundle/Controller/"
    type:     annotation
    prefix:   /tjr-admin

labs_limitless_tpl:
    resource: "@LabsLimitlessTplBundle/Controller/"
    type:     annotation
    prefix:   /tpladmin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

