# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    api.youtube.key:  'AIzaSyBn7E1usBBkFhWfpoYzmnnYsin-9-G0PJk'
    api.youtube.channel.id: 'UCfxFA4sCsppvbcRred327KQ'

services:
    draft_create:
        class: Labs\AdminBundle\Services\Draft
        arguments: ["@doctrine.orm.entity_manager"]

    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
            - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    date.interval.extension:
        class: Labs\AdminBundle\Twig\DateIntervalExtension
        public: false
        tags:
            - {name: twig.extension}

    youtube_api.service:
        class: Labs\AdminBundle\Services\YoutubeApi
        arguments: ['@service_container']

    upload.get_image_path:
        class: Labs\AdminBundle\Services\getImagePath
        arguments: ['@doctrine.orm.entity_manager']
